name: paginable
description: Paginable is a Flutter package which makes pagination easier by providing more functionality on top of native widgets.
version: 1.1.0
homepage: https://github.com/chinkysight/paginable

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
